server:
  port: 8302

management:
  #暴露所有接口
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api

eureka:
  client:
    serviceUrl:
      defaultZone: http://kings:1234@register.ws.com/eureka/

  instance:
    health-check-url: http://localhost:${server.servlet.context-path}/actuator/health
    status-page-url: http://localhost:${server.servlet.context-path}/actuator/info
    home-page-url: htts://localhost:${server.servlet.context-path}/
    
spring:
  application:
    name: king-boot-order
        

  
king-boot-order:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule

info:
  description: sringboot order

feign:
  client:
    config:
      default:
        #和hystrix一起配置
        connectTimeout: 4000
        readTimeout: 4000
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 4000  
  


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000