info:
  description: sringboot dubbo
spring:
  main:
    allow-bean-definition-overriding: true

  boot:
    admin:
      client:
        url: http://localhost:7000
        period: 30000
        instance:
          health-url: http://localhost:7001/actuator/health
          service-url: http://localhost:7001
          management-url: http://localhost:7001/actuator
          name: king-boot-dubbo
        username: ws
        password: 1234

dubbo:
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
    status: server
  registry:
    address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182
    id: my-registry
    protocol: zookeeper
  scan:
    base-packages: com.kingboot.service.impl

  #endpoints.health.sensitive =
management:
  #暴露所有接口
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 7001
