server:
  port: 8301
  servlet:
    context-path:

management:
  #暴露所有接口
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api

eureka:
  client:
    serviceUrl:
      defaultZone: http://kings:1234@register.ws.com/eureka/

  instance:
    health-check-url: http://localhost:${server.port}actuator/health
    status-page-url: http://localhost:${server.port}/actuator/info
    home-page-url: htts://localhost:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15

spring:
  application:
    name: king-boot-user
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      #采样百分比、开发环境可以设置为1表示全部，生成用默认
      probability: 1

  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
    url: jdbc:mysql://localhost:3306/boot-user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-idle: 8
        max-wait: 1  
    
#mapper
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - com.kingboot.common.config.mybatis.mapper.MybatisMysqlMapper
    - tk.mybatis.mapper.common.MySqlMapper
  notEmpty: true
  identity: MYSQL
  safe-delete: true
#mapper

mybatis:
  type-aliases-package: com.kingboot.basic.dao.boot.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
feign:
  client:
    config:
      default:
        #和hystrix一起配置
        connectTimeout: 4000
        readTimeout: 4000
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 4000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

king-boot-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    listOfServers: localhost:8301


info:
  description: sringboot user

ribbon:
  eureka:
    enabled: true