server:
  port: 8301
  servlet:
    context-path:

management:
  #暴露所有接口
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api

eureka:
  client:
    serviceUrl:
      defaultZone: http://kings:1234@register.ws.com/eureka/

  instance:
    health-check-url: http://localhost:${server.port}actuator/health
    status-page-url: http://localhost:${server.port}/actuator/info
    home-page-url: htts://localhost:${server.port}

spring:
  application:
    name: king-boot-user
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      #采样百分比、开发环境可以设置为1表示全部，生成用默认
      probability: 1


feign:
  client:
    config:
      default:
        #和hystrix一起配置
        connectTimeout: 4000
        readTimeout: 4000
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 4000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

king-boot-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    listOfServers: localhost:8301


info:
  description: sringboot user

ribbon:
  eureka:
    enabled: true