server:
  port: 8401
spring:
  application:
    name: king-boot-api-gateway
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://kings:1234@register.ws.com/eureka/

#\u81EA\u5B9A\u4E49\u8DEF\u7531\u6620\u5C04
zuul:
  routes:
    king-boot-user:
      path: /apigateway/u/**
      service-id: king-boot-user
    king-boot-order:
      path: /apigateway/o/**
      service-id: king-boot-order
    auth-service:
      path: /auth/**
      service-id: king-boot-auth
      strip-prefix: false
  strip-prefix: false
