spring:
  application:
    name: king-boot-auth
server:
  port: 8402
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      defaultZone: http://kings:1234@register.ws.com/eureka/  